@startuml StateMachine

' States
ZeroState: PendingOp (optional)
AccumulatorState: DigitAccumulator\nPendingOp (optional)
AccumulatorDecimalState: DigitAccumulator\nPendingOp (optional)
state ComputedState {
    state ComputedState1
    ComputedState1: Number
    state ComputedState2
    ComputedState2 : Number\nPendingOp
}
ErrorState: MathOperationError

' Inputs
' Zero
ZeroState -> ZeroState : Zero (ignore)
' AccumulatorState -> AccumulatorState : Digit
' AccumulatorDecimalState -> AccumulatorDecimalState : Digit
ComputedState -up-> ZeroState : Zero
' ErrorState

' NonZeroDigit
ZeroState --> AccumulatorState : NonZeroDigit
AccumulatorState -> AccumulatorState : Digit
AccumulatorDecimalState -> AccumulatorDecimalState : Digit
ComputedState -up-> AccumulatorState : NonZeroDigit
' ErrorState

' DecimalSeparator
ZeroState -[#Brown]> AccumulatorDecimalState : Separator
AccumulatorState -[#Brown]> AccumulatorDecimalState : Separator
AccumulatorDecimalState -[#Brown]> AccumulatorDecimalState : Separator (ignore)
ComputedState -up[#Brown]-> AccumulatorDecimalState : Separator
' ErrorState

' MathOp
ZeroState -[#Blue]-> ComputedState2 : Op
AccumulatorState -[#Blue]-> ComputedState2 : Op
AccumulatorDecimalState -[#Blue]-> ComputedState2 : Op
ComputedState -[#Blue]-> ComputedState2 : Op
' ErrorStateData

' Equals
ZeroState -[#Green]-> ComputedState1 : Equals
AccumulatorState -[#Green]-> ComputedState1 : Equals
AccumulatorState -[#Red,bold]-> ErrorState : Equals
AccumulatorDecimalState -[#Green]-> ComputedState1 : Equals
AccumulatorDecimalState -[#Red,bold]-> ErrorState : Equals
ComputedState2 -right[#Green]-> ComputedState1 : Equals
' ErrorState

' Clear
[*] -> ZeroState : Clear

@enduml
